import os

import tensorflow as tf
import numpy as np

from src.utils.plots import plot_training

path_base_dir="../simulation/ID_"
path_ending_dir="/keras_logs/"


def extract_tf_log(path="", tag=""):
    """
    Extract tensorflow log data from a file post-run
    TODO: add support of list input of tags?
    :param path: Path to events.out log file generated by tensorflow
    :param tag: The data to extract
    :return: A numpy array with the tag-values sorted in ascending epochs
    """
    data=[]
    for e in tf.train.summary_iterator(path):
        for v in e.summary.value:
            if v.tag==tag:
                data.append(v.simple_value)
    return np.array(data) if data is not None else None


for sid in range(52):
    file_path = path_base_dir + str(sid) + path_ending_dir
    file_name = os.listdir(file_path)[0]  # Not so nice but for our current setup this is fine with single files in dirs
    y_label = plot_training(y_label="[%]",
                          train_loss=extract_tf_log(path=file_path + file_name, tag="epoch_loss"),
                          val_loss=extract_tf_log(path=file_path + file_name, tag="epoch_val_loss"),
                          title="Training metrics for plot %s"%str(sid),
                          sid=str(sid))
